import { useState } from "react";
import { useTasks, useUpdateTask, useCreateTask, useDeleteTask } from "@/hooks/use-tasks";
import { useCourses } from "@/hooks/use-courses";
import { format, isToday, isTomorrow, addDays, isBefore } from "date-fns";
import { Calendar as CalendarIcon, CheckCircle2, Circle, Clock, Plus, Trash2, RefreshCw } from "lucide-react";
import { Button } from "@/components/button";
import { Input } from "@/components/input";
import { LoadingSpinner } from "@/components/loading";
import { apiRequest } from "@/lib/queryClient";
import { queryClient } from "@/lib/queryClient";
import { api } from "@shared/routes";

const DAY_OPTIONS = [
  { label: "Sunday", value: 0 },
  { label: "Monday", value: 1 },
  { label: "Tuesday", value: 2 },
  { label: "Wednesday", value: 3 },
  { label: "Thursday", value: 4 },
  { label: "Friday", value: 5 },
  { label: "Saturday", value: 6 },
];

const RECURRENCE_LABELS: Record<string, string> = {
  weekly: "Weekly",
  biweekly: "Every 2 weeks",
  monthly: "Monthly",
};

export default function Dashboard() {
  const { data: tasks, isLoading: tasksLoading } = useTasks();
  const { data: courses, isLoading: coursesLoading } = useCourses();
  const updateTask = useUpdateTask();
  const createTask = useCreateTask();
  const deleteTask = useDeleteTask();
  
  const [newTaskTitle, setNewTaskTitle] = useState("");
  const [newTaskDate, setNewTaskDate] = useState("");
  const [recurrenceRule, setRecurrenceRule] = useState<"" | "weekly" | "biweekly" | "monthly">("");
  const [recurrenceDayOfWeek, setRecurrenceDayOfWeek] = useState<number | "">("");
  const [showRecurrence, setShowRecurrence] = useState(false);

  if (tasksLoading || coursesLoading) return <LoadingSpinner />;

  const enrolledCourses = courses?.filter(c => c.isEnrolled) || [];
  
  const allEvents = [
    ...(tasks || []).map(t => ({ ...t, eventType: 'task' as const })),
    ...enrolledCourses.flatMap(c => 
      (c.assignments || []).map(a => ({ 
        ...a, 
        eventType: 'assignment' as const, 
        courseName: c.name,
        courseCode: c.code
      }))
    )
  ].sort((a, b) => new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime());

  // Only show next 7 days (plus overdue items)
  const sevenDaysFromNow = addDays(new Date(), 7);
  const upcomingEvents = allEvents.filter(e => {
    if ('completed' in e && e.completed) return false;
    const eventDate = new Date(e.dueDate);
    return isBefore(eventDate, sevenDaysFromNow);
  });
  
  const handleToggleTask = (id: number, currentStatus: boolean | null) => {
    updateTask.mutate({ id, completed: !currentStatus });
  };

  const handleCreateTask = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTaskTitle || !newTaskDate) return;
    
    const payload: any = {
      title: newTaskTitle,
      dueDate: new Date(newTaskDate),
      completed: false,
      isAutoGenerated: false,
    };

    if (recurrenceRule) {
      payload.recurrenceRule = recurrenceRule;
      if (recurrenceDayOfWeek !== "") {
        payload.recurrenceDayOfWeek = Number(recurrenceDayOfWeek);
      }
    }

    createTask.mutate(payload, {
      onSuccess: () => {
        setNewTaskTitle("");
        setNewTaskDate("");
        setRecurrenceRule("");
        setRecurrenceDayOfWeek("");
        setShowRecurrence(false);
      }
    });
  };

  const handleDeleteTask = async (id: number, hasRecurrence: boolean) => {
    if (hasRecurrence) {
      if (window.confirm("Delete just this task, or all occurrences in the series?\n\nClick OK to delete all occurrences, Cancel to delete only this one.")) {
        await apiRequest("DELETE", `${api.tasks.delete.path.replace(":id", String(id))}?deleteAll=true`);
        queryClient.invalidateQueries({ queryKey: [api.tasks.list.path] });
      } else {
        deleteTask.mutate(id);
      }
    } else {
      deleteTask.mutate(id);
    }
  };

  const getDateGroupLabel = (date: Date) => {
    if (isToday(date)) return "Today";
    if (isTomorrow(date)) return "Tomorrow";
    if (isBefore(date, new Date())) return "Overdue";
    if (isBefore(date, addDays(new Date(), 7))) return format(date, "EEEE");
    return format(date, "MMM d, yyyy");
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <header>
        <h1 className="text-4xl font-display font-bold">Welcome back.</h1>
        <p className="text-muted-foreground mt-2 text-lg">Here's your academic workflow for this week.</p>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Timeline Column */}
        <div className="lg:col-span-8 space-y-6">
          <div className="bg-card rounded-2xl p-6 shadow-sm border border-border">
            <div className="flex items-center gap-3 mb-6">
              <CalendarIcon className="text-primary w-6 h-6" />
              <h2 className="text-2xl font-display font-bold">Upcoming Deadlines</h2>
            </div>
            
            {upcomingEvents.length === 0 ? (
              <div className="text-center py-12">
                <div className="w-16 h-16 bg-secondary rounded-full flex items-center justify-center mx-auto mb-4">
                  <CheckCircle2 className="w-8 h-8 text-muted-foreground" />
                </div>
                <p className="text-lg font-medium">All caught up!</p>
                <p className="text-muted-foreground">You have no upcoming tasks or assignments.</p>
              </div>
            ) : (
              <div className="space-y-4">
                {upcomingEvents.map((event, idx) => {
                  const eventDate = new Date(event.dueDate);
                  const isOverdue = isBefore(eventDate, new Date()) && !isToday(eventDate);
                  const task = event.eventType === 'task' ? event as any : null;
                  const isRecurring = task && (task.recurrenceRule || task.recurrenceParentId);
                  
                  return (
                    <div 
                      key={`${event.eventType}-${event.id}`}
                      className="group flex gap-4 p-4 rounded-xl hover:bg-secondary transition-colors"
                      data-testid={`event-${event.eventType}-${event.id}`}
                    >
                      <div className="w-16 flex flex-col items-center pt-1 shrink-0 text-center">
                        <span className={`text-xs font-bold uppercase tracking-wider ${isOverdue ? 'text-destructive' : 'text-primary'}`}>
                          {format(eventDate, "MMM")}
                        </span>
                        <span className="text-2xl font-display font-bold leading-none">
                          {format(eventDate, "dd")}
                        </span>
                      </div>
                      
                      <div className="flex-1">
                        <div className="flex items-start justify-between">
                          <div>
                            {event.eventType === 'assignment' && (
                              <span className="text-xs font-bold text-primary/80 bg-primary/10 px-2 py-0.5 rounded-full mb-1 inline-block">
                                {(event as any).courseCode} Assignment
                              </span>
                            )}
                            {event.eventType === 'task' && (
                              <span className="text-xs font-bold text-accent-foreground/60 bg-accent px-2 py-0.5 rounded-full mb-1 inline-block">
                                {isRecurring ? (
                                  <span className="flex items-center gap-1">
                                    <RefreshCw className="w-3 h-3" />
                                    {task.recurrenceRule ? RECURRENCE_LABELS[task.recurrenceRule] : "Recurring"} Task
                                  </span>
                                ) : "Personal Task"}
                              </span>
                            )}
                            <h3 className={`text-lg font-semibold ${(event as any).completed ? "line-through text-muted-foreground" : ""}`}>
                              {(event as any).title || (event as any).name}
                            </h3>
                            {event.eventType === 'assignment' && (
                              <p className="text-sm text-muted-foreground">
                                {(event as any).weight != null ? `Weight: ${(event as any).weight}% • ` : ""}Type: {(event as any).type ?? "—"}
                              </p>
                            )}
                          </div>
                          
                          {event.eventType === 'task' && (
                            <div className="flex items-center gap-2">
                              <button 
                                onClick={() => handleToggleTask(event.id, (event as any).completed)}
                                className="text-muted-foreground hover:text-primary transition-colors"
                                data-testid={`button-toggle-task-${event.id}`}
                              >
                                {(event as any).completed ? (
                                  <CheckCircle2 className="w-6 h-6 text-primary" />
                                ) : (
                                  <Circle className="w-6 h-6" />
                                )}
                              </button>
                              <button
                                onClick={() => handleDeleteTask(event.id, !!isRecurring)}
                                className="text-muted-foreground hover:text-destructive opacity-0 group-hover:opacity-100 transition-all"
                                data-testid={`button-delete-task-${event.id}`}
                              >
                                <Trash2 className="w-4 h-4" />
                              </button>
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        </div>

        {/* Quick Add Task Column */}
        <div className="lg:col-span-4 space-y-6">
          <div className="bg-card rounded-2xl p-6 shadow-sm border border-border sticky top-8">
            <div className="flex items-center gap-3 mb-6">
              <CheckCircle2 className="text-primary w-6 h-6" />
              <h2 className="text-xl font-display font-bold">Quick Task</h2>
            </div>
            
            <form onSubmit={handleCreateTask} className="space-y-4">
              <Input 
                placeholder="What needs to be done?" 
                value={newTaskTitle}
                onChange={e => setNewTaskTitle(e.target.value)}
                data-testid="input-task-title"
              />
              <Input 
                type="date" 
                value={newTaskDate}
                onChange={e => setNewTaskDate(e.target.value)}
                data-testid="input-task-date"
              />

              {/* Recurrence toggle */}
              <button
                type="button"
                onClick={() => { setShowRecurrence(!showRecurrence); if (showRecurrence) { setRecurrenceRule(""); setRecurrenceDayOfWeek(""); } }}
                className="flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors"
                data-testid="button-toggle-recurrence"
              >
                <RefreshCw className={`w-4 h-4 transition-colors ${showRecurrence ? 'text-primary' : ''}`} />
                {showRecurrence ? "Remove recurrence" : "Make this recurring"}
              </button>

              {showRecurrence && (
                <div className="space-y-3 bg-secondary/50 rounded-xl p-3">
                  <div>
                    <label className="text-xs font-semibold text-muted-foreground mb-1.5 block">Repeat</label>
                    <select
                      className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary"
                      value={recurrenceRule}
                      onChange={e => setRecurrenceRule(e.target.value as any)}
                      data-testid="select-recurrence-rule"
                    >
                      <option value="">Choose frequency...</option>
                      <option value="weekly">Weekly</option>
                      <option value="biweekly">Every 2 weeks</option>
                      <option value="monthly">Monthly</option>
                    </select>
                  </div>
                  {recurrenceRule && (
                    <div>
                      <label className="text-xs font-semibold text-muted-foreground mb-1.5 block">On which day? (optional)</label>
                      <select
                        className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary"
                        value={recurrenceDayOfWeek}
                        onChange={e => setRecurrenceDayOfWeek(e.target.value === "" ? "" : Number(e.target.value))}
                        data-testid="select-recurrence-day"
                      >
                        <option value="">Same day each time</option>
                        {DAY_OPTIONS.map(d => (
                          <option key={d.value} value={d.value}>{d.label}</option>
                        ))}
                      </select>
                    </div>
                  )}
                  {recurrenceRule && (
                    <p className="text-xs text-muted-foreground">
                      Will auto-generate {recurrenceRule === "weekly" ? "12" : recurrenceRule === "biweekly" ? "6" : "3"} instances automatically.
                    </p>
                  )}
                </div>
              )}

              <Button 
                type="submit" 
                className="w-full" 
                isLoading={createTask.isPending}
                disabled={!newTaskTitle || !newTaskDate}
                data-testid="button-add-task"
              >
                <Plus className="w-4 h-4 mr-2" /> {recurrenceRule ? "Add Recurring Task" : "Add Task"}
              </Button>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}
