import { useState } from "react";
import { useTasks, useUpdateTask, useCreateTask, useDeleteTask } from "@/hooks/use-tasks";
import { useCourses } from "@/hooks/use-courses";
import { format, isToday, isTomorrow, addDays, isBefore } from "date-fns";
import { Calendar as CalendarIcon, CheckCircle2, Circle, Clock, Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/button";
import { Input } from "@/components/input";
import { LoadingSpinner } from "@/components/loading";

export default function Dashboard() {
  const { data: tasks, isLoading: tasksLoading } = useTasks();
  const { data: courses, isLoading: coursesLoading } = useCourses();
  const updateTask = useUpdateTask();
  const createTask = useCreateTask();
  const deleteTask = useDeleteTask();
  
  const [newTaskTitle, setNewTaskTitle] = useState("");
  const [newTaskDate, setNewTaskDate] = useState("");

  if (tasksLoading || coursesLoading) return <LoadingSpinner />;

  const enrolledCourses = courses?.filter(c => c.isEnrolled) || [];
  
  // Aggregate all deadlines (assignments + tasks)
  const allEvents = [
    ...(tasks || []).map(t => ({ ...t, eventType: 'task' as const })),
    ...enrolledCourses.flatMap(c => 
      (c.assignments || []).map(a => ({ 
        ...a, 
        eventType: 'assignment' as const, 
        courseName: c.name,
        courseCode: c.code
      }))
    )
  ].sort((a, b) => new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime());

  const upcomingEvents = allEvents.filter(e => !('completed' in e) || !e.completed);
  
  const handleToggleTask = (id: number, currentStatus: boolean | null) => {
    updateTask.mutate({ id, completed: !currentStatus });
  };

  const handleCreateTask = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTaskTitle || !newTaskDate) return;
    createTask.mutate({
      title: newTaskTitle,
      dueDate: new Date(newTaskDate),
      completed: false,
      isAutoGenerated: false
    }, {
      onSuccess: () => {
        setNewTaskTitle("");
        setNewTaskDate("");
      }
    });
  };

  const getDateGroupLabel = (date: Date) => {
    if (isToday(date)) return "Today";
    if (isTomorrow(date)) return "Tomorrow";
    if (isBefore(date, new Date())) return "Overdue";
    if (isBefore(date, addDays(new Date(), 7))) return format(date, "EEEE");
    return format(date, "MMM d, yyyy");
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <header>
        <h1 className="text-4xl font-display font-bold">Welcome back.</h1>
        <p className="text-muted-foreground mt-2 text-lg">Here's your academic workflow for this week.</p>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Timeline Column */}
        <div className="lg:col-span-8 space-y-6">
          <div className="bg-card rounded-2xl p-6 shadow-sm border border-border">
            <div className="flex items-center gap-3 mb-6">
              <CalendarIcon className="text-primary w-6 h-6" />
              <h2 className="text-2xl font-display font-bold">Upcoming Deadlines</h2>
            </div>
            
            {upcomingEvents.length === 0 ? (
              <div className="text-center py-12">
                <div className="w-16 h-16 bg-secondary rounded-full flex items-center justify-center mx-auto mb-4">
                  <CheckCircle2 className="w-8 h-8 text-muted-foreground" />
                </div>
                <p className="text-lg font-medium">All caught up!</p>
                <p className="text-muted-foreground">You have no upcoming tasks or assignments.</p>
              </div>
            ) : (
              <div className="space-y-4">
                {upcomingEvents.map((event, idx) => {
                  const eventDate = new Date(event.dueDate);
                  const isOverdue = isBefore(eventDate, new Date()) && !isToday(eventDate);
                  
                  return (
                    <div 
                      key={`${event.eventType}-${event.id}`}
                      className="group flex gap-4 p-4 rounded-xl hover:bg-secondary transition-colors"
                    >
                      <div className="w-16 flex flex-col items-center pt-1 shrink-0 text-center">
                        <span className={`text-xs font-bold uppercase tracking-wider ${isOverdue ? 'text-destructive' : 'text-primary'}`}>
                          {format(eventDate, "MMM")}
                        </span>
                        <span className="text-2xl font-display font-bold leading-none">
                          {format(eventDate, "dd")}
                        </span>
                      </div>
                      
                      <div className="flex-1">
                        <div className="flex items-start justify-between">
                          <div>
                            {event.eventType === 'assignment' && (
                              <span className="text-xs font-bold text-primary/80 bg-primary/10 px-2 py-0.5 rounded-full mb-1 inline-block">
                                {(event as any).courseCode} Assignment
                              </span>
                            )}
                            {event.eventType === 'task' && (
                              <span className="text-xs font-bold text-accent-foreground/60 bg-accent px-2 py-0.5 rounded-full mb-1 inline-block">
                                Personal Task
                              </span>
                            )}
                            <h3 className={`text-lg font-semibold ${(event as any).completed ? "line-through text-muted-foreground" : ""}`}>
                              {(event as any).title || (event as any).name}
                            </h3>
                            {event.eventType === 'assignment' && (
                              <p className="text-sm text-muted-foreground">
                                Weight: {(event as any).weight}% • Type: {(event as any).type}
                              </p>
                            )}
                          </div>
                          
                          {event.eventType === 'task' && (
                            <div className="flex items-center gap-2">
                              <button 
                                onClick={() => handleToggleTask(event.id, (event as any).completed)}
                                className="text-muted-foreground hover:text-primary transition-colors"
                              >
                                {(event as any).completed ? (
                                  <CheckCircle2 className="w-6 h-6 text-primary" />
                                ) : (
                                  <Circle className="w-6 h-6" />
                                )}
                              </button>
                              <button
                                onClick={() => deleteTask.mutate(event.id)}
                                className="text-muted-foreground hover:text-destructive opacity-0 group-hover:opacity-100 transition-all"
                              >
                                <Trash2 className="w-4 h-4" />
                              </button>
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        </div>

        {/* Quick Add Task Column */}
        <div className="lg:col-span-4 space-y-6">
          <div className="bg-card rounded-2xl p-6 shadow-sm border border-border sticky top-8">
            <div className="flex items-center gap-3 mb-6">
              <CheckCircle2 className="text-primary w-6 h-6" />
              <h2 className="text-xl font-display font-bold">Quick Task</h2>
            </div>
            
            <form onSubmit={handleCreateTask} className="space-y-4">
              <Input 
                placeholder="What needs to be done?" 
                value={newTaskTitle}
                onChange={e => setNewTaskTitle(e.target.value)}
              />
              <Input 
                type="date" 
                value={newTaskDate}
                onChange={e => setNewTaskDate(e.target.value)}
              />
              <Button 
                type="submit" 
                className="w-full" 
                isLoading={createTask.isPending}
                disabled={!newTaskTitle || !newTaskDate}
              >
                <Plus className="w-4 h-4 mr-2" /> Add Task
              </Button>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}
