import { pgTable, text, serial, integer, boolean, timestamp, varchar, jsonb, decimal } from "drizzle-orm/pg-core";
import { relations, sql } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// --- Auth Tables (Mandatory for Replit Auth) ---
export const sessions = pgTable("sessions", {
  sid: varchar("sid").primaryKey(),
  sess: jsonb("sess").notNull(),
  expire: timestamp("expire").notNull(),
});

export const users = pgTable("users", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  email: varchar("email").unique(),
  firstName: varchar("first_name"),
  lastName: varchar("last_name"),
  profileImageUrl: varchar("profile_image_url"),
  university: varchar("university"),
  bio: text("bio"),
  googleCalendarEmbedUrl: text("google_calendar_embed_url"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// --- App Tables ---
export const courses = pgTable("courses", {
  id: serial("id").primaryKey(),
  code: text("code").notNull(),
  name: text("name").notNull(),
  section: text("section").notNull(),
  term: text("term").notNull(),
  createdBy: varchar("created_by").notNull().references(() => users.id),
  createdAt: timestamp("created_at").defaultNow(),
});

export const courseStudents = pgTable("course_students", {
  id: serial("id").primaryKey(),
  courseId: integer("course_id").notNull().references(() => courses.id),
  userId: varchar("user_id").notNull().references(() => users.id),
  joinedAt: timestamp("joined_at").defaultNow(),
});

export const syllabi = pgTable("syllabi", {
  id: serial("id").primaryKey(),
  courseId: integer("course_id").notNull().references(() => courses.id),
  uploadedBy: varchar("uploaded_by").notNull().references(() => users.id),
  fileUrl: text("file_url"),
  rawText: text("raw_text"),
  parsedContent: jsonb("parsed_content"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const assignments = pgTable("assignments", {
  id: serial("id").primaryKey(),
  courseId: integer("course_id").notNull().references(() => courses.id),
  name: text("name").notNull(),
  type: text("type").notNull(),
  dueDate: timestamp("due_date").notNull(),
  weight: decimal("weight").notNull(),
  maxScore: decimal("max_score").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const userGrades = pgTable("user_grades", {
  id: serial("id").primaryKey(),
  userId: varchar("user_id").notNull().references(() => users.id),
  assignmentId: integer("assignment_id").notNull().references(() => assignments.id),
  score: decimal("score"),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const tasks = pgTable("tasks", {
  id: serial("id").primaryKey(),
  userId: varchar("user_id").notNull().references(() => users.id),
  assignmentId: integer("assignment_id").references(() => assignments.id),
  title: text("title").notNull(),
  dueDate: timestamp("due_date").notNull(),
  completed: boolean("completed").default(false),
  isAutoGenerated: boolean("is_auto_generated").default(false),
  // Recurrence fields (T003)
  recurrenceRule: text("recurrence_rule"), // null | "weekly" | "biweekly" | "monthly"
  recurrenceDayOfWeek: integer("recurrence_day_of_week"), // 0=Sun … 6=Sat
  recurrenceParentId: integer("recurrence_parent_id"), // links generated instances back to the parent
  createdAt: timestamp("created_at").defaultNow(),
});

// Pre-lecture prep cache (T002)
export const prepCache = pgTable("prep_cache", {
  id: serial("id").primaryKey(),
  courseId: integer("course_id").notNull().references(() => courses.id).unique(),
  content: jsonb("content").notNull(), // { summary, readingPrompts[], practiceQuestions[], topics[] }
  generatedAt: timestamp("generated_at").defaultNow(),
});

// Study resource links per assignment (T004)
export const assignmentResources = pgTable("assignment_resources", {
  id: serial("id").primaryKey(),
  assignmentId: integer("assignment_id").notNull().references(() => assignments.id).unique(),
  resources: jsonb("resources").notNull(), // { title, url, platform }[]
  generatedAt: timestamp("generated_at").defaultNow(),
});

// --- Zod Schemas ---
export const insertCourseSchema = createInsertSchema(courses).omit({ id: true, createdBy: true, createdAt: true });

export const insertAssignmentSchema = createInsertSchema(assignments).omit({ id: true, createdAt: true }).extend({
  dueDate: z.coerce.date(),
  weight: z.union([z.string(), z.number()]).transform(v => Number(v)),
  maxScore: z.union([z.string(), z.number()]).transform(v => Number(v))
});
export const updateAssignmentSchema = insertAssignmentSchema.partial();

export const insertUserGradeSchema = createInsertSchema(userGrades).omit({ id: true, userId: true, updatedAt: true }).extend({
  score: z.union([z.string(), z.number()]).transform(v => Number(v))
});

export const insertTaskSchema = createInsertSchema(tasks).omit({ id: true, userId: true, createdAt: true }).extend({
  dueDate: z.coerce.date(),
  recurrenceRule: z.enum(["weekly", "biweekly", "monthly"]).optional().nullable(),
  recurrenceDayOfWeek: z.number().min(0).max(6).optional().nullable(),
});
export const updateTaskSchema = insertTaskSchema.partial();

// --- Types ---
export const updateUserProfileSchema = z.object({
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  university: z.string().optional(),
  bio: z.string().optional(),
  profileImageUrl: z.string().optional(),
  googleCalendarEmbedUrl: z.string().optional().nullable(),
});
export type UpdateUserProfile = z.infer<typeof updateUserProfileSchema>;

export type UpsertUser = typeof users.$inferInsert;
export type User = typeof users.$inferSelect;
export type Course = typeof courses.$inferSelect;
export type CourseStudent = typeof courseStudents.$inferSelect;
export type Syllabus = typeof syllabi.$inferSelect;
export type Assignment = typeof assignments.$inferSelect;
export type UserGrade = typeof userGrades.$inferSelect;
export type Task = typeof tasks.$inferSelect;
export type PrepCache = typeof prepCache.$inferSelect;
export type AssignmentResources = typeof assignmentResources.$inferSelect;

export type CourseResponse = Course & {
  assignments: Assignment[];
  syllabi: Syllabus[];
  studentCount: number;
  isEnrolled?: boolean;
};

export type GradeTrackerItem = {
  assignment: Assignment;
  grade: UserGrade | null;
};

export type CourseGradeTrackerResponse = Course & {
  trackerItems: GradeTrackerItem[];
};

export type ResourceLink = {
  title: string;
  url: string;
  platform: string;
};

export type PrepContent = {
  summary: string;
  readingPrompts: string[];
  practiceQuestions: string[];
  topics: string[];
  generatedAt: string;
};
